web:
  build: ./app
  command: 'bash -c ''gunicorn scienceapi.wsgi:application'''
  working_dir: /app
  env_file: .env
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
shell:
  build: ./app
  command: bash
  working_dir: /app
  environment:
    PORT: 8008
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8008:8008'
  links:
    - herokuPostgresql
  volumes:
    - './app:/app'
herokuPostgresql:
  image: postgres
